// Auto-generated by Entirety
// Place this file in your project root to get autocomplete for Entirety aliases.

declare module "entirety" {
  export interface EntiretyAliases {
    Lodash: Promise<typeof import("lodash")> & {
      [K in keyof typeof import("lodash")]: typeof import("lodash")[K] extends (...args: infer A) => infer R
        ? (...args: A) => Promise<Awaited<R>>
        : Promise<typeof import("lodash")[K]>
    };
    Axios: Promise<typeof import("axios")> & {
      [K in keyof typeof import("axios")]: typeof import("axios")[K] extends (...args: infer A) => infer R
        ? (...args: A) => Promise<Awaited<R>>
        : Promise<typeof import("axios")[K]>
    };
    React: Promise<typeof import("react")> & {
      [K in keyof typeof import("react")]: typeof import("react")[K] extends (...args: infer A) => infer R
        ? (...args: A) => Promise<Awaited<R>>
        : Promise<typeof import("react")[K]>
    };
    MUI: Promise<typeof import("@mui/material")> & {
      [K in keyof typeof import("@mui/material")]: typeof import("@mui/material")[K] extends (...args: infer A) => infer R
        ? (...args: A) => Promise<Awaited<R>>
        : Promise<typeof import("@mui/material")[K]>
    };
  }

  export interface EntiretyType extends EntiretyAliases {
    use<T extends string>(pkg: T): any;
    (pkg: string): any;
    register(alias: string, pkg: string): void;
    register(map: Record<string, string>): void;
    extend(alias: string, pkg: string): void;
    extend(map: Record<string, string>): void;
    aliases: Record<string, string>;
    clearCache(): void;
    configure(options: { autoInstall?: boolean, packageManager?: string, installCwd?: string, silent?: boolean }): any;
    config: { autoInstall: boolean, packageManager: string | null, installCwd: string | null, silent: boolean };
  }

  const Entirety: EntiretyType;
  export default Entirety;
}
