import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { aliases as defaultAliases } from "./aliases.js";

/**
 * Generate a TypeScript declaration file for Entirety aliases.
 */
export function generateDts(customAliases = defaultAliases, outputPath = "entirety-env.d.ts") {
  let content = `// Auto-generated by Entirety
// Place this file in your project root to get autocomplete for Entirety aliases.

declare module "entirety" {
  export interface EntiretyAliases {
`;

  for (const [alias, pkg] of Object.entries(customAliases)) {
    content += `    ${alias}: Promise<typeof import("${pkg}")> & {\n`;
    content += `      [K in keyof typeof import("${pkg}")]: typeof import("${pkg}")[K] extends (...args: infer A) => infer R\n`;
    content += `        ? (...args: A) => Promise<Awaited<R>>\n`;
    content += `        : Promise<typeof import("${pkg}")[K]>\n`;
    content += `    };\n`;
  }

  content += `  }

  export interface EntiretyType extends EntiretyAliases {
    use<T extends string>(pkg: T): any;
    (pkg: string): any;
    register(alias: string, pkg: string): void;
    register(map: Record<string, string>): void;
    extend(alias: string, pkg: string): void;
    extend(map: Record<string, string>): void;
    aliases: Record<string, string>;
    clearCache(): void;
    configure(options: { autoInstall?: boolean, packageManager?: string, installCwd?: string, silent?: boolean }): any;
    config: { autoInstall: boolean, packageManager: string | null, installCwd: string | null, silent: boolean };
  }

  const Entirety: EntiretyType;
  export default Entirety;
}
`;

  writeFileSync(outputPath, content);
  console.log(`\x1b[32m✔\x1b[0m Generated ${outputPath} with types for ${Object.keys(customAliases).length} aliases.`);
}

// Support running directly via CLI
if (process.argv[1] === new URL(import.meta.url).pathname || process.argv[1] === import.meta.filename) {
  const outputPath = process.argv[2] || "entirety-env.d.ts";
  generateDts(defaultAliases, join(process.cwd(), outputPath));
}
